apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
  namespace: dev-jupyter-data-science
spec:
  selector: {}
  template:
    metadata:
      name: job-test
    spec:
      serviceAccountName: dev-jupyter-data-science-svc-acc
      containers:
        - name: daily-automation-tmpcleanup
          image: docker.io/thescomcontainers/copy-notebooks:1.0.0
      restartPolicy: Never
