apiVersion: v1
kind: Pod
metadata:
  name: dev-jupyter-data-science
  labels:
    app: dev-jupyter-data-science
  namespace: dev-jupyter-data-science
spec:
  serviceAccountName: dev-jupyter-data-science-svc-acc
  containers:
    - name: dev-jupyter-data-science
      image: "docker.io/prasadgugulla/datascience:1.0.3"
      ports:
        - containerPort: 9003
      volumeMounts:
        - name: notebooks-pv
          mountPath: /notebooks
  volumes:
    - name: notebooks-pv
      persistentVolumeClaim:
        claimName: notebooks-pvc
