kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-rolebind
  namespace: dev-jupyter-data-science
subjects:
  - kind: ServiceAccount
    name: dev-jupyter-data-science-svc-acc
    namespace: dev-jupyter-data-science
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin