apiVersion: v1
kind: Pod
metadata:
  name: prod-jupyter-data-science
  labels:
    app: prod-jupyter-data-science
  namespace: jupyter-data-science
spec:
  serviceAccountName: jupyter-data-science-svc-acc
  containers:
    - name: prod-jupyter-data-science
      image: "docker.io/prasadgugulla/datascience:1.0.6"
      ports:
        - containerPort: 9003
      volumeMounts:
        - name: prod-notebooks-pv
          mountPath: /notebooks-pv
  volumes:
    - name: prod-notebooks-pv
      persistentVolumeClaim:
        claimName: prod-notebooks-pvc
