apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: prod-jupyter-data-science
  name: prod-jupyter-data-science
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prod-jupyter-data-science
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: prod-jupyter-data-science
    spec:
      serviceAccountName: jupyter-data-science-svc-acc
      containers:
        - name: prod-jupyter-data-science
          image: "jpacerqueira83/jupyter_datascience:latest-stable-version-2.4.5"
          resources: {}
          volumeMounts:
            - name: notebook-pv
              mountPath: /home/notebookuser/notebooks
            - name: tmp-pv
              mountPath: /tmp
      resources: {}
      volumes:
        - name: notebook-pv
          persistentVolumeClaim:
            claimName: notebook-pvc
        - name: tmp-pv
          persistentVolumeClaim:
            claimName: tmp-pvc
status: {}
