apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: dev-jupyter-data-science
spec:
  selector:
    matchLabels:
      app: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
    spec:
      serviceAccountName: elk-svc-acc
      containers:
        # - env:
        #     - name: LS_JAVA_OPTS
        #       value: "-Xmx256m -Xms256m"
        #     - name: xpack.monitoring.elasticsearch.ssl.verification_mode
        #       value: "none"
        #     - name: xpack.monitoring.enabled
        #       value: "true"
        - name: elastic
          image: "prasadgugulla/elastic:7.16.3"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elastic-pv
              mountPath: /elastic-pv
      volumes:
        - name: elastic-pv
          persistentVolumeClaim:
            claimName: elastic-pvc
