apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  namespace: dev-jupyter-data-science
spec:
  selector:
    matchLabels:
      app: elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
    spec:
      serviceAccountName: elk-svc-acc
  containers:
    - env:
        - name: LS_JAVA_OPTS
          value: "-Xmx1024m -Xms1024m"
        - name: network.host
          value: "0.0.0.0"
        #- name: http.port
        # value: "9200"
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: "elk-cluster"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "true"
        - name: xpack.security.http.ssl.keystore.path
          value: "/usr/share/elasticsearch/config/http.p12"
        - name: discovery.type
          value: "single-node"
        - name: path.data
          value: "/elastic-pv/data"
        - name: elastic
          image: "prasadgugulla/elastic:7.16.3"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elastic-pv
              mountPath: /elastic-pv
      volumes:
        - name: elastic-pv
          persistentVolumeClaim:
            claimName: elastic-pvc
