apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
  namespace: dev-jupyter-data-science
spec:
  serviceAccountName: elk-svc-acc
  containers:
    - name: kibana
      image: "docker.io/elastic/kibana:7.16.2"
      ports:
        - containerPort: 5601