apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
  namespace: dev-jupyter-data-science
spec:
  serviceAccountName: elk-svc-acc
  containers:
      - env:
          #- name: ELASTICSEARCH_URL
            #value: "https:fdadmin:password12//8dbb924d-0278-4dc4-9311-1b0a463be046.btdl9c3f09gqti6k4svg.databases.appdomain.cloud:30865"
          - name: ELASTICSEARCH_HOSTS
            value: "https://elastic.devsfcluster-56118b4b985711fc98241a723e4ef72a-0000.eu-de.containers.appdomain.cloud:9200"
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: password12
          - name: XPACK_SECURITY_ENABLED
            value: "true"
          - name: xpack.security.transport.ssl.enabled
            value: "true"
          - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
            value: "/usr/share/kibana/config/elasticsearch-ca.pem"
          - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
            value: "certificate"
          - name: csp_strict
            value: "true"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: xpack.encryptedSavedObjects.encryptionKey
            value: "6259fd26f5e8ffcb1adecdda95ad1ba3"
          - name: xpack.reporting.encryptionKey
            value: "b6e12e1e0de2fe00b60489ed09c5339f"
          - name: xpack.security.encryptionKey
            value: "007e35b6730fdaaaaf2f85dddc24043b"
        name: kibana
        image: "prasadgugulla/kibana:7.16.3"
        ports:
          - containerPort: 5601
        #command: ["./bin/kibana -c /usr/share/kibana/config/kibana.yml"]