apiVersion: v1
kind: Pod
metadata:
  name: logstash
  labels:
    app: logstash
  namespace: dev-jupyter-data-science
spec:
  serviceAccountName: elk-svc-acc
  containers:
    - name: logstash
      image: "logstash/logstash:7.16.2"
      ports:
        - containerPort: 9600
      volumeMounts:
        - name: logstash-pv
          mountPath: /logstash_dir
  volumes:
    - name: logstash-pv
      persistentVolumeClaim:
        claimName: logstash-pvc


