apiVersion: v1
kind: Pod
metadata:
  name: logstash
  labels:
    app: logstash
  namespace: dev-jupyter-data-science
spec:
  serviceAccountName: elk-svc-acc
  containers:
    - env:
        - name: LS_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: ELASTICSEARCH_URL
          value: https://8dbb924d-0278-4dc4-9311-1b0a463be046.btdl9c3f09gqti6k4svg.databases.appdomain.cloud:30865
      name: logstash
      image: "prasadgugulla/logstash:7.10.0"
      ports:
        - containerPort: 9600
      volumeMounts:
        - name: notebooks-pv
          mountPath: /notebooks-pv
  volumes:
    - name: notebooks-pv
      persistentVolumeClaim:
        claimName: notebooks-pvc
