http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "https://172.17.41.218:9200" ]

#xpack.monitoring.enabled: "true"
#elasticsearch.username: "elastic"
#elasticsearch.password: 'password12'
#elasticsearch.hosts: ["https://elastic.devsfcluster-56118b4b985711fc98241a723e4ef72a-0000.eu-de.containers.appdomain.cloud"]
#elasticsearch.ssl.verification_mode: "none"

xpack:
  monitoring:
    enabled: true
    elasticsearch:
      username: "elastic"
      password: "password12"
      hosts: ["https://172.17.41.218:9200"]
      ssl:
        verification_mode: none